# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db: seed (foodID: or created alongside the db with db: setup).
#
# Examples: 
#
#   cities = City.create(foodID: [{ name:  'Chicago' }, { name:  'Copenhagen' }])
#   Mayor.create(foodID: name:  'Emanuel', city:  cities.first)

Food.create(foodID: 0, menuCategory:  "salad", name: "salad", price: 2.89, onMenuNow: true) 
Food.create(foodID: 1, menuCategory:  "pizza", name: "cheese", price: 4.89, onMenuNow: true) 
Food.create(foodID: 2, menuCategory:  "pizza", name: "pepperoni", price: 5.49, onMenuNow: true) 
Food.create(foodID: 3, menuCategory:  "pizza", name: "bbq_chicken", price: 6.89, onMenuNow: true) 
Food.create(foodID: 5, menuCategory:  "pizza", name: "hawaiian", price: 6.89, onMenuNow: true) 
Food.create(foodID: 6, menuCategory:  "pizza", name: "margherita", price: 5.49, onMenuNow: true) 
Food.create(foodID: 7, menuCategory:  "pizza", name: "margheritin", price: 5.49, onMenuNow: true) 
Food.create(foodID: 8, menuCategory:  "pizza", name: "vegan", price: 5.39, onMenuNow: true) 
Food.create(foodID: 9, menuCategory:  "calzone", name: "cheese", price: 5.89, onMenuNow: true) 
Food.create(foodID: 10, menuCategory:  "calzone", name: "pepperoni", price: 6.49, onMenuNow: true) 
Food.create(foodID: 11, menuCategory:  "calzone", name: "bbq_chicken", price: 7.89, onMenuNow: true) 
Food.create(foodID: 12, menuCategory:  "calzone", name: "meat_lovers", price: 7.89, onMenuNow: true) 
Food.create(foodID: 13, menuCategory:  "calzone", name: "hawaiian", price: 7.89, onMenuNow: true) 
Food.create(foodID: 14, menuCategory:  "calzone", name: "margherita", price: 6.49, onMenuNow: true) 
Food.create(foodID: 15, menuCategory:  "calzone", name: "margheritin", price: 6.49, onMenuNow: true) 
Food.create(foodID: 16, menuCategory:  "calzone", name: "vegan", price: 6.39, onMenuNow: true) 
Food.create(foodID: 17, menuCategory:  "soup", name: "beef_bean_chili_8oz", price: 2.89, onMenuNow: true) 
Food.create(foodID: 18, menuCategory:  "soup", name: "beef_bean_chili_12oz", price: 3.89, onMenuNow: true) 
Food.create(foodID: 19, menuCategory:  "soup", name: "soup_of_day_8oz", price: 2.89, onMenuNow: true) 
Food.create(foodID: 20, menuCategory:  "soup", name: "soup_of_day_12oz", price: 3.89, onMenuNow: true) 
Food.create(foodID: 21, menuCategory:  "drinks", name: "coffee_12oz", price: 1.45, onMenuNow: true) 
Food.create(foodID: 22, menuCategory:  "drinks", name: "coffee_16oz", price: 1.80, onMenuNow: true) 
Food.create(foodID: 23, menuCategory:  "drinks", name: "coffee_20oz", price: 2.05, onMenuNow: true) 
Food.create(foodID: 24, menuCategory:  "drinks", name: "tea_12oz", price: 1.19, onMenuNow: true) 
Food.create(foodID: 25, menuCategory:  "drinks", name: "tea_16oz", price: 1.59, onMenuNow: true) 
Food.create(foodID: 26, menuCategory:  "drinks", name: "tea_20oz", price: 1.89, onMenuNow: true) 
Food.create(foodID: 27, menuCategory:  "drinks", name: "apple_12oz", price: 1.95, onMenuNow: true) 
Food.create(foodID: 28, menuCategory:  "drinks", name: "apple_16oz", price: 2.35, onMenuNow: true) 
Food.create(foodID: 29, menuCategory:  "drinks", name: "apple_20oz", price: 2.65, onMenuNow: true) 
Food.create(foodID: 30, menuCategory:  "drinks", name: "smoothie_16oz", price: 5.89, onMenuNow: true) 
Food.create(foodID: 31, menuCategory:  "sandwich", name: "baker_bacon", price: 6.89, onMenuNow: true) 
Food.create(foodID: 32, menuCategory:  "sandwich", name: "bbq_chicken", price: 6.89, onMenuNow: true) 
Food.create(foodID: 33, menuCategory:  "sandwich", name: "classic_blt", price: 4.89, onMenuNow: true) 
Food.create(foodID: 34, menuCategory:  "sandwich", name: "classic_italian", price: 6.89, onMenuNow: true) 
Food.create(foodID: 35, menuCategory:  "sandwich", name: "darly_divine", price: 6.89, onMenuNow: true) 
Food.create(foodID: 36, menuCategory:  "sandwich", name: "farrand_fodder", price: 6.89, onMenuNow: true) 
Food.create(foodID: 37, menuCategory:  "sandwich", name: "hallett_ham", price: 6.89, onMenuNow: true) 
Food.create(foodID: 38, menuCategory:  "sandwich", name: "libby_licious", price: 6.89, onMenuNow: true) 
Food.create(foodID: 39, menuCategory:  "sandwich", name: "parisian_grilled_cheese", price: 5.89, onMenuNow: true) 
Food.create(foodID: 40, menuCategory:  "sandwich", name: "roast_beef_pepper_melt", price: 7.89, onMenuNow: true) 
Food.create(foodID: 41, menuCategory:  "sandwich", name: "tofu_mozzarella", price: 5.89, onMenuNow: true) 
Food.create(foodID: 42, menuCategory:  "sandwich", name: "tuna_melt", price: 5.89, onMenuNow: true) 
Food.create(foodID: 43, menuCategory:  "sandwich", name: "turkey_bacon_club", price: 6.89, onMenuNow: true) 
Food.create(foodID: 44, menuCategory:  "sandwich", name: "turkey_jalapeno_melt", price: 6.89, onMenuNow: true) 
Food.create(foodID: 45, menuCategory:  "sandwich", name: "veggie_club", price: 6.89, onMenuNow: true) 
Food.create(foodID: 68, menuCategory:  "dessert", name: "gelato_8oz", price: 2.89, onMenuNow: true) 
Food.create(foodID: 69, menuCategory:  "dessert", name: "gelato_12oz", price: 3.69, onMenuNow: true) 
Food.create(foodID: 70, menuCategory:  "dessert", name: "sundae_8oz", price: 2.89, onMenuNow: true) 
Food.create(foodID: 71, menuCategory:  "dessert", name: "sundae_12oz", price: 3.69, onMenuNow: true) 
Food.create(foodID: 72, menuCategory:  "dessert", name: "milkshake", price: 5.89, onMenuNow: true) 
Food.create(foodID: 73, menuCategory:  "dessert", name: "avalanche", price: 5.89, onMenuNow: true) 
Food.create(foodID: 74, menuCategory:  "dessert", name: "hot_chocolate_12oz", price: 2.85, onMenuNow: true) 
Food.create(foodID: 74, menuCategory:  "dessert", name: "hot_chocolate_16oz", price: 3.55, onMenuNow: true) 
Food.create(foodID: 75, menuCategory:  "dessert", name: "hot_chocolate_20oz", price: 3.85, onMenuNow: true) 
Food.create(foodID: 76, menuCategory:  "gluten_free", name: "hallett_ham_sandwich", price: 6.89, onMenuNow: true) 
Food.create(foodID: 77, menuCategory:  "gluten_free", name: "veggie_club_sandwich", price: 6.89, onMenuNow: true) 
Food.create(foodID: 78, menuCategory:  "gluten_free", name: "roast_turkey_wrap", price: 6.89, onMenuNow: true) 
Food.create(foodID: 79, menuCategory:  "gluten_free", name: "heavenly_hummus_wrap", price: 6.89, onMenuNow: true) 

Ingredient.create(ingredientID: 0, menuCategory: "condiment", name: "ranch", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 1, menuCategory: "condiment", name: "spicy_ranch", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 2, menuCategory: "condiment", name: "mustard", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 3, menuCategory: "condiment", name: "brown_mustard", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 4, menuCategory: "condiment", name: "mayo", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 5, menuCategory: "condiment", name: "bbq", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 6, menuCategory: "condiment", name: "hot_sauce",customizationStyle: "sandwich" ) 
Ingredient.create(ingredientID: 7, menuCategory: "condiment", name: "pesto", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 8, menuCategory: "condiment", name: "hummus", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 9, menuCategory: "condiment", name: "honey_mustard", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 10, menuCategory: "condiment", name: "italian", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 11, menuCategory: "condiment", name: "avocado", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 12, menuCategory: "bread_choice", name: "white_baguette", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 13, menuCategory: "bread_choice", name: "wheat_baguette", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 14, menuCategory: "bread_choice", name: "white_ciabatta", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 15, menuCategory: "bread_choice", name: "potato_rosemary_ciabatta", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 16, menuCategory: "bread_choice", name: "focaccia", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 17, menuCategory: "bread_choice", name: "7_grain", customizationStyle: "sandwich") 
Ingredient.create(ingredientID: 18, menuCategory: "greens", name: "field_greens", customizationStyle: "salad") 
Ingredient.create(ingredientID: 19, menuCategory: "greens", name: "romaine", customizationStyle: "salad") 
Ingredient.create(ingredientID: 20, menuCategory: "greens", name: "spinach", customizationStyle: "salad") 
Ingredient.create(ingredientID: 21, menuCategory: "veggies", name: "tomato", customizationStyle: "salad") 
Ingredient.create(ingredientID: 22, menuCategory: "veggies", name: "onion", customizationStyle: "salad") 
Ingredient.create(ingredientID: 23, menuCategory: "veggies", name: "olives", customizationStyle: "salad") 
Ingredient.create(ingredientID: 24, menuCategory: "veggies", name: "mushrooms", customizationStyle: "salad") 
Ingredient.create(ingredientID: 25, menuCategory: "veggies", name: "bell_peppers", customizationStyle: "salad") 
Ingredient.create(ingredientID: 26, menuCategory: "veggies", name: "banana_peppers", ) 
Ingredient.create(ingredientID: 27, menuCategory: "veggies", name: "broccoli", customizationStyle: "salad") 
Ingredient.create(ingredientID: 28, menuCategory: "veggies", name: "cucumber", customizationStyle: "salad") 
Ingredient.create(ingredientID: 29, menuCategory: "veggies", name: "jalapeno", customizationStyle: "salad") 
Ingredient.create(ingredientID: 30, menuCategory: "veggies", name: "corn", customizationStyle: "salad") 
Ingredient.create(ingredientID: 31, menuCategory: "veggies", name: "garbanzo_beans", customizationStyle: "salad") 
Ingredient.create(ingredientID: 32, menuCategory: "veggies", name: "carrots", customizationStyle: "salad") 
Ingredient.create(ingredientID: 33, menuCategory: "cheese", name: "cheddar", customizationStyle: "salad") 
Ingredient.create(ingredientID: 34, menuCategory: "cheese", name: "feta", customizationStyle: "salad") 
Ingredient.create(ingredientID: 35, menuCategory: "cheese", name: "parmesan", customizationStyle: "salad") 
Ingredient.create(ingredientID: 36, menuCategory: "cheese", name: "blue", customizationStyle: "salad") 
Ingredient.create(ingredientID: 37, menuCategory: "cheese", name: "mozzarella", customizationStyle: "salad") 
Ingredient.create(ingredientID: 38, menuCategory: "protein", name: "turkey", customizationStyle: "salad") 
Ingredient.create(ingredientID: 39, menuCategory: "protein", name: "chicken", customizationStyle: "salad") 
Ingredient.create(ingredientID: 40, menuCategory: "protein", name: "tofu", customizationStyle: "salad") 
Ingredient.create(ingredientID: 41, menuCategory: "protein", name: "bacon", customizationStyle: "salad") 
Ingredient.create(ingredientID: 42, menuCategory: "protein", name: "tuna", customizationStyle: "salad") 
Ingredient.create(ingredientID: 43, menuCategory: "protein", name: "salami", customizationStyle: "salad") 
Ingredient.create(ingredientID: 44, menuCategory: "protein", name: "pepperoni", customizationStyle: "salad") 
Ingredient.create(ingredientID: 45, menuCategory: "protein", name: "roast_beef", customizationStyle: "salad") 
Ingredient.create(ingredientID: 46, menuCategory: "protein", name: "ham", customizationStyle: "salad") 
Ingredient.create(ingredientID: 47, menuCategory: "toppings", name: "croutons", customizationStyle: "salad") 
Ingredient.create(ingredientID: 48, menuCategory: "toppings", name: "cranberry_raisins", customizationStyle: "salad") 
Ingredient.create(ingredientID: 49, menuCategory: "toppings", name: "sesame_seeds", customizationStyle: "salad") 
Ingredient.create(ingredientID: 50, menuCategory: "dressing", name: "ranch", customizationStyle: "salad") 
Ingredient.create(ingredientID: 51, menuCategory: "dressing", name: "spicy_ranch", customizationStyle: "salad") 
Ingredient.create(ingredientID: 52, menuCategory: "dressing", name: "parmesan_peppercorn", customizationStyle: "salad") 
Ingredient.create(ingredientID: 53, menuCategory: "dressing", name: "red_wine_vinaigrette", customizationStyle: "salad") 
Ingredient.create(ingredientID: 54, menuCategory: "dressing", name: "raspberry_vinaigrette", customizationStyle: "salad") 
Ingredient.create(ingredientID: 55, menuCategory: "dressing", name: "balsamic_vinaigrette", customizationStyle: "salad") 
Ingredient.create(ingredientID: 56, menuCategory: "dressing", name: "caesar", customizationStyle: "salad") 
Ingredient.create(ingredientID: 57, menuCategory: "dressing", name: "italian", customizationStyle: "salad") 
Ingredient.create(ingredientID: 58, menuCategory: "dressing", name: "blue_cheese", customizationStyle: "salad") 
Ingredient.create(ingredientID: 59, menuCategory: "dressing", name: "honey_mustard", customizationStyle: "salad") 
Ingredient.create(ingredientID: 60, menuCategory: "dressing", name: "balsamic_vinegar_and_oil", customizationStyle: "salad") 
